apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: second-app
  template: 
    metadata:
      labels: 
        app: second-app
    spec: 
      containers:
        - name: second-node
          image: stancic/kub-first-app
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: third-node
        #   image: stancic/kub-second-app