apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80 # outside port which is exposed
      targetPort: 8080 # inside of the container
    # - protocol: 'TCP'
    #   port: 80 # outside port which is exposed
    #   targetPort: 8080 # inside of the container
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels: 
    group: example
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: second-app
  template: 
    metadata:
      labels: 
        app: second-app
    spec: 
      containers:
        - name: second-node
          image: stancic/kub-first-app
        # - name: third-node
        #   image: stancic/kub-second-app
