apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  selector:
    matchLabels:
      app: tasks
  replicas: 1
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: stancic/kub-demo-tasks:latest
        env:
          - name: AUTH_ADDRESS
            value: "auth-service.default"
          - name: TASKS_FOLDER
            value: tasks